import type { Candidate } from "./catalog";

/** Deterministic catalog for browser tests, selected with CATALOG=fixture. Not real venues. */
export const fixtureCandidates: Candidate[] = [
  {
    id: "fx-kanda-books",
    sourceName: "神田测试书店",
    sourceGroup: "fixture",
    status: "published",
    verificationNotes: "Fixture.",
    location: {
      name: "神田テスト書店",
      alternateNames: ["Kanda Test Books", "神田測試書店"],
      category: "bookstores",
      tags: ["chineseBooks", "events"],
      address: "東京都千代田区神田神保町1-1",
      ward: "chiyoda",
      lat: 35.6958,
      lng: 139.76,
      website: "https://example.com/kanda",
      sources: [
        { url: "https://example.com/kanda/about", label: "Kanda Test Books", primary: true },
        { url: "https://example.org/review", label: "Example Review", primary: false },
      ],
      verifiedOn: "2026-09-30",
      hours: {
        ja: "11:00–19:00（月曜定休）",
        en: "11:00–19:00 (closed Mon)",
        "zh-Hant": "11:00–19:00（週一公休）",
      },
      description: {
        ja: "中国語の人文書を扱う書店。",
        en: "Bookshop specialising in Chinese-language humanities.",
        "zh-Hant": "專營中文人文書籍的書店。",
      },
    },
  },
  {
    id: "fx-chiyoda-art",
    sourceName: "Chiyoda Art Room",
    sourceGroup: "fixture",
    status: "published",
    verificationNotes: "Fixture.",
    location: {
      name: "千代田アートルーム",
      alternateNames: ["Chiyoda Art Room"],
      category: "galleries",
      tags: ["gallery", "contemporaryArt"],
      address: "東京都千代田区九段南1-1",
      ward: "chiyoda",
      lat: 35.6945,
      lng: 139.7515,
      sources: [{ url: "https://example.com/chiyoda-art", label: "Chiyoda Art Room", primary: true }],
      verifiedOn: "2026-09-30",
      description: {
        ja: "現代美術の小さな展示室。",
        en: "Small room for contemporary art.",
        "zh-Hant": "小型當代藝術展間。",
      },
    },
  },
  {
    id: "fx-shibuya-gallery",
    sourceName: "TEST Gallery",
    sourceGroup: "fixture",
    status: "published",
    verificationNotes: "Fixture with full-width name to exercise width normalization.",
    location: {
      name: "ＴＥＳＴ　Ｇａｌｌｅｒｙ",
      alternateNames: ["測試畫廊"],
      category: "galleries",
      tags: ["gallery", "photography"],
      address: "東京都渋谷区神宮前3-1",
      ward: "shibuya",
      lat: 35.6703,
      lng: 139.7071,
      sources: [{ url: "https://example.com/test-gallery", label: "TEST Gallery", primary: true }],
      verifiedOn: "2026-09-30",
      description: {
        ja: "写真展を中心とするギャラリー。",
        en: "Gallery focused on photography shows.",
        "zh-Hant": "以攝影展為主的藝廊。",
      },
    },
  },
  {
    id: "fx-shinagawa-tea",
    sourceName: "茶居",
    sourceGroup: "fixture",
    status: "published",
    verificationNotes: "Fixture with no hours, website or photo.",
    location: {
      name: "テスト茶館 茶居",
      alternateNames: ["Chaju Tea House", "茶居"],
      category: "foodDrink",
      tags: ["chineseTea", "cafe"],
      address: "東京都品川区旗の台3-1",
      ward: "shinagawa",
      lat: 35.6053,
      lng: 139.7038,
      sources: [{ url: "https://example.com/chaju", label: "Chaju", primary: false }],
      verifiedOn: "2026-09-30",
      description: {
        ja: "烏龍茶と点心の茶館。",
        en: "Teahouse serving oolong and dim sum.",
        "zh-Hant": "供應烏龍茶與點心的茶館。",
      },
    },
  },
  {
    id: "fx-draft",
    sourceName: "未公開ドラフト書店",
    sourceGroup: "fixture",
    status: "draft",
    verificationNotes: "Fixture: draft with a complete location must stay hidden.",
    location: {
      name: "未公開ドラフト書店",
      alternateNames: ["Hidden Draft Books"],
      category: "bookstores",
      tags: ["chineseBooks"],
      address: "東京都台東区上野1-1",
      ward: "taito",
      lat: 35.712,
      lng: 139.775,
      sources: [{ url: "https://example.com/draft", label: "Draft", primary: true }],
      verifiedOn: "2026-09-30",
      description: { ja: "ドラフト。", en: "Draft.", "zh-Hant": "草稿。" },
    },
  },
  {
    id: "fx-out-of-scope",
    sourceName: "川口スタジオ",
    sourceGroup: "fixture",
    status: "published",
    verificationNotes: "Fixture: marked published but outside the 23 wards.",
    location: {
      name: "川口スタジオ（範囲外）",
      alternateNames: ["Kawaguchi Out Of Scope Studio"],
      category: "community",
      tags: ["studio"],
      address: "埼玉県川口市江戸袋1-1",
      ward: "kawaguchi",
      lat: 35.8177,
      lng: 139.757,
      sources: [{ url: "https://example.com/kawaguchi", label: "Kawaguchi", primary: true }],
      verifiedOn: "2026-09-30",
      description: { ja: "範囲外。", en: "Out of scope.", "zh-Hant": "範圍外。" },
    },
  },
  {
    id: "fx-unresolved",
    sourceName: "@unresolved_handle",
    sourceGroup: "fixture",
    status: "draft",
    verificationNotes: "Fixture: social handle without a verified venue.",
  },
];
